### PR TITLE
Add support for python 2

### PR DESCRIPTION
**Pull request by kovidgoyal**
The test suite passes on both python 3.4 and python 2.7.10

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I have added lots of other commits fixing various bugs/mem leaks and adding features, see the individual commits. All bug fixes/new features come with tests. All test pass on python 2.7 and 3.4

**Comment by akheron** [comment]
Hi and thanks for the pull request. Everything looks very good!

I added you as a contributor so you can make further modifications yourself. We can also discuss transferring the ownership to you, because I don't really have enough time to maintain this.

**Comment by kovidgoyal** [comment]
Sure if you wish to transfer ownership to me, I am happy to take it over.

**Comment by kovidgoyal** [comment]
Just in case you dont get my email, I have deleted my fork, and I am fine with keeping you as a contributor.

**Pull request merged**
